name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [20.15.0]

    env:
      PORT: ${{ secrets.PORT }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      MONGOURL: ${{ secrets.MONGOURL }}

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Start server
      run: npm start &
      
    - name: Wait for server to be ready
      run: sleep 15

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build . -t ${{ secrets.DOCKER_USERNAME }}/payment_gateway

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/payment_gateway

  deploy:
   needs: build
   runs-on: [aws-ec2]
   steps:
     - name: Pull Image from docker hub
       run: docker pull payment_gateway
     - name: Delete old container
       run: docker rm -f payment_gateway-container
     - name: Run docker container
       run: docker run -d -p 3000:3000 --name payment_gateway-container payment_gateway
